import { useEffect, useState } from "react"
import { v4 as uuidv4 } from "uuid"
import { CarFront, Info, Bike, Copy } from "lucide-react"
import type { InspectionData, ResultChannel, VehicleCategory } from "@/lib/inspection"
import { cn } from "@/lib/utils"

const CAR_TYPES: Record<VehicleCategory, string[]> = { private: ["Xe dưới 6 chỗ", "Xe từ 6 đến 11 chỗ", "Xe trên 11 chỗ"], commercial: ["Xe dưới 6 chỗ", "Xe từ 6 đến 11 chỗ", "Xe trên 11 chỗ"], truck: ["Xe tải dưới 3 tấn", "Xe tải từ 3 đến 8 tấn", "Xe tải trên 8 tấn"], tractor: ["Đầu kéo kéo sơ-mi rơ-moóc"], special: ["Xe chuyên dụng"] }
const MOTO_CATEGORIES = ["Mô tô 2 bánh", "Xe gắn máy (bao gồm xe máy điện) và các loại xe cơ giới tương tự"]
const MOTO_TYPES: Record<string, string[]> = { "Mô tô 2 bánh": ["Dưới 50 cc", "Trên 50 cc", "Mô tô 3 bánh"], "Xe gắn máy (bao gồm xe máy điện) và các loại xe cơ giới tương tự": ["Xe máy điện", "Các loại xe khác"] }
const CATEGORY_LABELS: Record<VehicleCategory, string> = { private: "Xe không kinh doanh vận tải", commercial: "Xe kinh doanh vận tải", truck: "Xe tải", tractor: "Xe đầu kéo", special: "Xe chuyên dụng" }
const CHANNELS: { value: ResultChannel; label: string; disabled?: boolean }[] = [{ value: "telegram", label: "Telegram" }, { value: "zalo", label: "Zalo", disabled: true }, { value: "sms", label: "SMS", disabled: true }]

type VehicleMode = "car" | "motorbike"
export function StepBasicInfo({ data, update }: { data: InspectionData; update: (patch: Partial<InspectionData>) => void }) {
  const [copied, setCopied] = useState(false)
  useEffect(() => { if (data.resultChannel === "telegram" && !data.telegramUuid) update({ telegramUuid: uuidv4() }) }, [data.resultChannel, data.telegramUuid, update])
  const copyUuid = async () => { await navigator.clipboard.writeText(data.telegramUuid); setCopied(true); window.setTimeout(() => setCopied(false), 1800) }
  const mode: VehicleMode = data.vehicleMode
  const types = mode === "motorbike" ? (MOTO_TYPES[data.vehicleCategory] ?? []) : data.vehicleCategory ? CAR_TYPES[data.vehicleCategory] : []
  const categories = mode === "motorbike" ? MOTO_CATEGORIES : (Object.keys(CATEGORY_LABELS) as VehicleCategory[])
  return <div className="flex flex-col gap-6">
    <header className="flex flex-col gap-1.5 text-center"><h2 className="text-2xl font-bold tracking-tight text-balance">Thông tin xe</h2><p className="text-sm leading-relaxed text-muted-foreground">Nhập thông tin để trợ lý tự động tra cứu phạt nguội.</p></header>
    <div className="flex flex-col gap-2"><label htmlFor="plate" className="text-sm font-semibold">Biển số xe</label><div className="mx-auto w-full max-w-[280px] rounded-xl border-[3px] border-foreground bg-card p-1 shadow-sm"><input id="plate" value={data.plate} onChange={(e) => update({ plate: e.target.value.toUpperCase() })} placeholder="51K-123.45" inputMode="text" autoComplete="off" className="w-full rounded-lg bg-card py-2.5 text-center font-mono text-2xl font-extrabold tracking-widest text-foreground placeholder:text-muted-foreground/40 focus:outline-none" /></div></div>
    <div className="flex flex-col gap-3 rounded-xl border border-input bg-card p-4 shadow-sm"><div className="flex items-center gap-2 text-primary"><CarFront className="size-5" /><span className="text-sm font-semibold text-foreground">Loại xe</span></div><p className="flex items-center gap-1 text-xs leading-relaxed text-muted-foreground"><Info className="size-3 shrink-0" />Chọn đúng loại xe để hiển thị hạng mục phù hợp.</p><div className="grid grid-cols-2 gap-2" role="radiogroup" aria-label="Loại xe"><label className={cn("flex cursor-pointer items-center justify-center gap-2 rounded-xl border px-3 py-3 text-sm font-semibold", mode === "car" ? "border-primary bg-primary text-primary-foreground" : "border-input text-muted-foreground")}><input className="sr-only" type="radio" name="vehicle-mode" checked={mode === "car"} onChange={() => update({ vehicleMode: "car", vehicleCategory: "", vehicleType: "" })} /><CarFront className="size-5" />Ô tô</label><label className={cn("flex cursor-pointer items-center justify-center gap-2 rounded-xl border px-3 py-3 text-sm font-semibold", mode === "motorbike" ? "border-primary bg-primary text-primary-foreground" : "border-input text-muted-foreground")}><input className="sr-only" type="radio" name="vehicle-mode" checked={mode === "motorbike"} onChange={() => update({ vehicleMode: "motorbike", vehicleCategory: "", vehicleType: "" })} /><Bike className="size-5" />Xe máy</label></div><div className="flex flex-col gap-2"><label htmlFor="vehicle-category" className="text-sm font-semibold">Hạng mục</label><select id="vehicle-category" value={data.vehicleCategory} onChange={(e) => update({ vehicleCategory: e.target.value as VehicleCategory, vehicleType: "" })} className={cn("h-12 w-full rounded-xl border border-input bg-card px-4 text-base font-medium focus:border-primary focus:outline-none", data.vehicleCategory ? "text-foreground" : "text-muted-foreground")}><option value="" disabled>Chọn hạng mục xe</option>{categories.map((category) => <option key={category} value={category}>{mode === "motorbike" ? category : CATEGORY_LABELS[category as VehicleCategory]}</option>)}</select></div><div className="flex flex-col gap-2"><label htmlFor="vehicle-type" className="text-sm font-semibold">Phân loại</label><select id="vehicle-type" value={data.vehicleType} disabled={!data.vehicleCategory} onChange={(e) => update({ vehicleType: e.target.value })} className="h-12 w-full rounded-xl border border-input bg-card px-4 text-base font-medium disabled:cursor-not-allowed disabled:opacity-50"><option value="" disabled>Chọn phân loại xe</option>{types.map((type) => <option key={type}>{type}</option>)}</select></div></div>
    <div className="flex flex-col gap-4 rounded-xl border border-input bg-card p-4 shadow-sm"><h3 className="text-sm font-semibold">Cách nhận kết quả</h3><div className="flex flex-wrap gap-4" role="radiogroup" aria-label="Kênh nhận kết quả">{CHANNELS.map((channel) => <label key={channel.value} className="flex cursor-pointer items-center gap-2 text-sm font-medium"><input type="radio" name="result-channel" value={channel.value} disabled={channel.disabled} checked={data.resultChannel === channel.value} onChange={() => update({ resultChannel: channel.value })} className="size-4 accent-primary" />{channel.label}</label>)}</div><div className="flex flex-col gap-2"><label htmlFor="phone" className="text-sm font-semibold">Số điện thoại</label><input id="phone" value={data.phoneNumber} onChange={(e) => update({ phoneNumber: e.target.value.replace(/[^0-9]/g, "") })} placeholder="Nhập số điện thoại" inputMode="tel" autoComplete="tel" className="h-12 rounded-xl border border-input bg-card px-4 text-base" /></div>{data.resultChannel === "telegram" && <div className="flex flex-col gap-2"><label htmlFor="telegram-uuid" className="text-sm font-semibold">UUID</label><div className="flex gap-2"><input id="telegram-uuid" readOnly value={data.telegramUuid} className="h-12 min-w-0 flex-1 rounded-xl border border-input bg-muted px-4 font-mono text-sm" /><button type="button" aria-label="Copy UUID" onClick={copyUuid} className="inline-flex h-12 shrink-0 items-center gap-2 rounded-xl border border-input px-4 text-sm font-semibold">{copied ? <Check className="size-4" /> : <Copy className="size-4" />}Copy</button></div></div>}</div>
  </div>
}
