"use client"

import { useState } from "react"
import { Check, FileCheck2, LockKeyhole } from "lucide-react"
import type { InspectionData } from "@/lib/inspection"
import { AuthenticationFailedError, checkVehicle, type FineCheckResult } from "@/lib/checkxe-api"

export function StepDocuments({ data, update, onSuccess }: { data: InspectionData; update: (patch: Partial<InspectionData>) => void; onSuccess: () => void }) {
  const [agreed, setAgreed] = useState(false); const [otp, setOtp] = useState(""); const [needsOtp, setNeedsOtp] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false)
  const connect = async () => { if (!agreed || loading) return; setLoading(true); setError(""); try { const result = await checkVehicle({ licensePlate: data.plate, vehicleType: data.vehicleCategory, vehicleSubType: data.vehicleType, phoneNumber: data.phoneNumber, otp: needsOtp ? otp : undefined }); update({ vehicleVerified: true, checkResult: result }); onSuccess(); } catch (err) { if (err instanceof AuthenticationFailedError) setNeedsOtp(true); else setError(err instanceof Error ? err.message : "Kết nối thất bại") } finally { setLoading(false) } }
  return <div className="flex flex-col gap-5"><header className="flex flex-col gap-1.5"><h1 className="text-2xl font-bold tracking-tight text-balance">Kết nối tài khoản giao thông</h1><p className="text-sm leading-relaxed text-muted-foreground">Kết nối tài khoản giao thông để trợ lý tự động tra cứu mỗi ngày</p></header><section className="flex flex-col gap-4 rounded-xl border border-input bg-card p-5 shadow-sm"><div className="flex items-start gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary"><FileCheck2 className="size-5" /></span><div className="flex flex-col gap-1"><h2 className="text-base font-semibold">Tự động tra cứu thông tin với Trợ lý ảo</h2><p className="text-sm leading-relaxed text-muted-foreground">Trợ lý ảo sẽ đại diện bạn kết nối và tự động tra cứu dữ liệu mỗi ngày.</p></div></div><p className="text-sm leading-relaxed text-muted-foreground">Kết nối tài khoản giao thông để nhận thông báo miễn phí khi xe có vi phạm. Dữ liệu của bạn được bảo mật và chỉ sử dụng cho mục đích tra cứu.</p><div className="flex items-center gap-2 rounded-lg bg-secondary/60 p-3 text-xs text-muted-foreground"><LockKeyhole className="size-4 shrink-0 text-primary" />Thông tin được mã hóa và bảo mật.</div>{needsOtp && <div className="flex flex-col gap-2"><label htmlFor="otp" className="text-sm font-semibold">Mã OTP</label><input id="otp" value={otp} onChange={(e) => setOtp(e.target.value)} placeholder="Nhập mã OTP 6 số" inputMode="numeric" className="h-11 rounded-xl border border-input px-3 text-sm" /><p className="text-xs leading-relaxed text-muted-foreground">Trợ lý ảo sẽ tự động tạo lại mật khẩu và thực hiện tra cứu lại. Vui lòng nhập OTP được gửi đến SĐT đã đăng ký.</p></div>}<label className="flex items-start gap-2 text-xs"><input type="checkbox" checked={agreed} onChange={(e) => setAgreed(e.target.checked)} className="mt-0.5 size-4 accent-primary" /><span>Tôi đồng ý ủy quyền và đã đọc <a href="#terms" className="font-semibold text-primary underline">Thỏa thuận ủy quyền &amp; Bảo mật dữ liệu</a>.</span></label>{error && <p role="alert" className="text-sm font-semibold text-destructive">{error}</p>}<button type="button" onClick={connect} disabled={!agreed || (needsOtp && otp.length < 6) || loading} className="h-11 rounded-xl bg-primary text-sm font-semibold text-primary-foreground disabled:opacity-40">{loading ? "Đang tra cứu..." : needsOtp ? "Nhập OTP và tra cứu lại" : "Kết nối ngay"}</button>{data.vehicleVerified && <p className="flex items-center gap-1 text-xs font-semibold text-success"><Check className="size-4" />Đã kết nối và sẵn sàng tra cứu</p>}</section></div>
}
