export type ResultChannel = "telegram" | "zalo" | "sms"
export type CheckxePayload = { licensePlate: string; vehicleType: string; vehicleSubType: string; phoneNumber: string; cccd?: string; otp?: string }
export type FineCheckResult = { status: "clear" | "fined"; licensePlate: string; vehicleType: string; plateColor: string; violation?: { error: string; time: string; location: string }; detection?: { unit: string; address: string; phone?: string }; resolution?: { unit: string; address: string; phone?: string } }
export class AuthenticationFailedError extends Error { code = "AUTHENTICATION_FAILED"; constructor() { super("AUTHENTICATION_FAILED") } }
type ApiResponse = { success?: boolean; data?: { ok?: boolean; errorCode?: string; message?: string; data?: { bienSo?: string; trangThai?: string; loaiXe?: string; mauBien?: string; loiViPham?: string; thoiGian?: string; diaDiem?: string; donViPhatHien?: string; diaChiPhatHien?: string; donViGiaiQuyet?: string; diaChiGiaiQuyet?: string } } }
export async function checkVehicle(payload: CheckxePayload): Promise<FineCheckResult> { const response = await fetch("/api/check-vehicle", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ bienSoXe: payload.licensePlate.replace(/[.\-\s]/g, "").toUpperCase(), cccd: payload.cccd ?? "", otp: payload.otp ?? "" }) }); const result = (await response.json()) as ApiResponse; if (result.data?.errorCode === "AUTHENTICATION_FAILED") throw new AuthenticationFailedError(); if (!response.ok || result.success === false || result.data?.ok === false) throw new Error(result.data?.message || "Kết nối thất bại"); const item = result.data?.data; const fined = Boolean(item?.loiViPham) || /phạt|vi phạm/i.test(item?.trangThai ?? ""); return { status: fined ? "fined" : "clear", licensePlate: item?.bienSo || payload.licensePlate, vehicleType: item?.loaiXe || "Ô tô", plateColor: item?.mauBien || "Nền mầu trắng, chữ và số màu đen", ...(fined && item?.loiViPham ? { violation: { error: item.loiViPham, time: item.thoiGian || "", location: item.diaDiem || "" }, detection: { unit: item.donViPhatHien || "", address: item.diaChiPhatHien || "" }, resolution: { unit: item.donViGiaiQuyet || "", address: item.diaChiGiaiQuyet || "" } } : {}) } }
const CACHE_KEY = "dangkiemonline:last-checkxe"
export type CachedCheckxe = CheckxePayload & { resultChannel: ResultChannel }
export function getCachedCheckxe(): CachedCheckxe | null { if (typeof window === "undefined") return null; try { const value = window.localStorage.getItem(CACHE_KEY); return value ? JSON.parse(value) : null } catch { return null } }
export function saveCachedCheckxe(value: CachedCheckxe) { if (typeof window !== "undefined") window.localStorage.setItem(CACHE_KEY, JSON.stringify(value)) }
